### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by wake-pop** [ntkien1904/DegFairGNN#1]
Why are the test dataset and the verification dataset the same?
`p = int(0.6 * idx.shape[0])
        pt = int(0.8 * idx.shape[0])
        self.idx_train = idx[:p]
        self.idx_val = idx[pt:]
        self.idx_test = idx[pt:]`

**Comment by ntkien1904** [comment]
Thanks for your interests!

I updated the code for validate set. Since we used fixed epochs instead of val set with early stopping in training, this wouldn't affect the performance. Best regards.
  
`self.idx_val = idx[p:pt]`
